PID for shooter
frc-team-342/frc-team342-rapid-react pull request #18
Opened 2022-02-07 23:51 UTC by ctorek

2022-02-08 00:01 UTC, 20MatthewNeal requested changes

2022-02-08 00:01 UTC, 20MatthewNeal commented on src/main/java/frc/robot/subsystems/OuttakeSubsystem.java
> +    double rpm = velocity * 29.296875;
Magical number

2022-02-08 00:01 UTC, 20MatthewNeal commented on src/main/java/frc/robot/subsystems/OuttakeSubsystem.java
> +    shootMotor2.config_kD(1, D);
statically imported constants, comment please.

2022-02-10 22:14 UTC, MatthewEdgmon commented on src/main/java/frc/robot/subsystems/OuttakeSubsystem.java
> +      // Only feed is the shooter is ready
change is to if

2022-02-10 22:20 UTC, MatthewEdgmon requested changes

2022-02-10 22:20 UTC, MatthewEdgmon commented on src/main/java/frc/robot/subsystems/OuttakeSubsystem.java
> +    shootMotor1.set(ControlMode.Velocity, setpoint);
Do we need shootMotor2 as well?

2022-02-10 22:22 UTC, MatthewEdgmon commented on src/main/java/frc/robot/subsystems/OuttakeSubsystem.java
> +    shootMotor1.set(ControlMode.Velocity, setpoint);
Nope.

2022-02-10 22:22 UTC, MatthewEdgmon approved these changes

2022-02-10 22:25 UTC, 20MatthewNeal approved these changes

2022-02-10 22:28 UTC, merged