Implementing climb limit switch
frc-team-342/frc-team342-rapid-react pull request #52
Opened 2022-04-19 21:44 UTC by VZamora5

2022-04-19 21:49 UTC, ctorek requested changes
test it babey!! ! !!! wooo yeah!!!! scringle

2022-04-19 21:49 UTC, ctorek commented on src/main/java/frc/robot/subsystems/ClimbSubsystem.java
> +    climbLimitSwitch = new DigitalInput(3);
Use a constant!! !! !!!!!

2022-04-19 22:00 UTC, jboutin020106 commented
Looks good to me.

2022-04-19 22:01 UTC, jboutin020106 approved these changes
Everything seems correct

2022-04-27 01:28 UTC, ctorek requested changes

2022-04-27 01:28 UTC, ctorek commented on src/main/java/frc/robot/subsystems/ClimbSubsystem.java
> +    climbLimitSwitch = new AnalogInput(3);
the constant was added but you didn't change this to use the constant

2022-04-27 01:28 UTC, ctorek commented on src/main/java/frc/robot/subsystems/ClimbSubsystem.java
> +
write a javadoc comment explaining why this is a comparison

2022-04-27 01:28 UTC, ctorek commented on src/main/java/frc/robot/subsystems/ClimbSubsystem.java
> +    sendable.addDoubleProperty("Climb limit switch", climbLimitSwitch::getValue, null);
change this to a boolean property that references `getLimitState()`

2022-04-30 18:38 UTC, ctorek approved these changes
waiting on test to merge

2022-05-10 22:34 UTC, ctorek commented
it works

2022-05-18 20:44 UTC, ctorek requested changes

2022-05-18 20:44 UTC, hazeltorek commented on src/main/java/frc/robot/subsystems/ClimbSubsystem.java
> +  double convertedPos;
private

2022-05-18 20:44 UTC, ctorek commented on src/main/java/frc/robot/Constants.java
> +        public static final double ROTATE_MAX_ANGLE = 4100;
comment with units here

2022-05-18 20:44 UTC, ctorek commented on src/main/java/frc/robot/subsystems/ClimbSubsystem.java
> +    pulse = new SensorCollection(leadClimbRotate);
is this the preferred way to instantiate these? i think this should be the following

```java
pulse = leadClimbRotate.getSensorCollection();
```

not sure if thats the correct method but same idea

2022-05-18 20:44 UTC, ctorek commented on src/main/java/frc/robot/subsystems/ClimbSubsystem.java
> +    sendable.addDoubleProperty("Position Var", () -> position, null);
when completed values from testing should be removed and any values that are staying should be adjusted to make sure they have correct units

2022-05-21 17:26 UTC, ctorek approved these changes

2022-06-07 22:37 UTC, ctorek approved these changes

2022-06-07 22:37 UTC, merged